# Generated by Django 4.2.16 on 2024-12-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Item Damaged'), ('INCORRECT', 'Incorrect Item'), ('DEFECTIVE', 'Defective'), ('NOT_NEEDED', 'No Longer Needed'), ('SIZE_ISSUE', 'Wrong Size'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Return Requested'), ('APPROVED', 'Return Approved'), ('REJECTED', 'Return Rejected'), ('PROCESSED', 'Return Processed')], default='REQUESTED', max_length=20)),
                ('return_tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='orders.order')),
            ],
        ),
    ]
